import './appController.js';
import './domController.js';
import './styles/reset.css';
import './styles/config.css';
import './styles/global.css';
import './styles/style.css';
import './styles/add_button.css';
import './styles/header.css';
import './styles/sidebar.css';
// import './styles/task.css';
// import './styles/radio.css';
// import './styles/task_modal.css';
import './styles/footer.css';